/// Seller dimension with identifier and location code.
table Sellers
	lineageTag: f0057750-dbe8-4431-ad1a-8c9325a5897f

	/// Unique seller identifier. Prefer Seller Geography fields for display.
	column 'Seller ID'
		dataType: string
		isHidden
		lineageTag: 2a09ae06-556e-496e-9d41-90f3bad0c719
		summarizeBy: none
		sourceColumn: Seller ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Seller postal code. Links to Seller Geography for location details.
	column 'Seller Zip Code'
		dataType: int64
		formatString: 0
		lineageTag: 4b3a85be-483c-473e-aa38-2be8b022c0bf
		summarizeBy: none
		sourceColumn: Seller Zip Code

		annotation SummarizationSetBy = Automatic

	partition Sellers = m
		mode: import
		source =
				let
				    Source = Sql.Database(__server, "ecommerce_lakehouse"),
				    fda_Sellers = Source{[Schema="fda",Item="Sellers"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(fda_Sellers,{"Seller City", "Seller State"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

